- src/components/Drawer.jsx
- src/components/table/user-row-item.jsx
- src/components/table/users-table.jsx
User Management - show menu, hide actions conditionally
> User Management - show menu, hide actions conditionally

- src/actions/index.js
- src/api/endpoints.js
- src/api/index.js
- src/api/search-index.js
- src/components/Drawer.jsx
- src/components/Main.jsx
- src/components/table/search-reports-table.jsx
- src/lib/constants.js
- src/lib/params.js
- src/pages/reports/components/allocation-round-filter.jsx
- src/pages/reports/components/country-filter.jsx
- src/pages/reports/components/ctn-number-filter.jsx
- src/pages/reports/components/gavi-date-filter.jsx
- src/pages/reports/components/gavi-wbs-filter.jsx
- src/pages/reports/components/mou-number-filter.jsx
- src/pages/reports/components/prepaid-status-filter.jsx
- src/pages/reports/components/purchase-order-filter.jsx
- src/pages/reports/components/vendor-filter.jsx
- src/pages/reports/constants.jsx
- src/pages/reports/index.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search-constants.jsx
- src/pages/reports/search.jsx
- src/sagas/collections.js
- src/sagas/search-reports.js
- src/selectors/collections.js
- src/slices/gavi.js
Added Gavi Reports page + filters
> Added Gavi Reports page + filters

- src/components/table/search-reports-table.jsx
- src/lib/constants.js
- src/styles/table-styles.js
> Table details, refresh fix

- src/components/App-Bar.jsx
> change logout url #170

- src/api/index.js
- src/components/Connected-Router-Watcher.jsx
- src/pages/users-portal/components/add-user-modal.jsx
- src/pages/users-portal/components/users-filter.jsx
- src/sagas/collections.js
- src/sagas/user.js
- src/selectors/user.js
- src/slices/index.js
- src/slices/user-groups.js
> GAVI: User management #166

- src/lib/constants.js
- src/pages/reports/components/approval-year-filter.jsx
- src/pages/reports/components/vaccine-type-filter.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search-constants.jsx
- src/selectors/collections.js
- src/slices/metadata.js
- src/slices/static.js
filters: Vaccine type filter, Approval year filter
> filters: Vaccine type filter, Approval year filter

- src/components/table/search-reports-table.jsx
- src/components/table/user-row-item.jsx
- src/components/table/users-table.jsx
User management: role doesn't show up #190
> User management: role doesn't show up #190

- src/lib/use-filters-queries.js
- src/pages/reports/components/search-filter.jsx
- src/pages/reports/components/search-reports-filters-root.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search-constants.jsx
create search filter: param called search + label Search
> create search filter: param called search + label Search

- src/components/table/search-reports-table.jsx
Expandable table: add Urgent field
> Expandable table: add Urgent field 

- src/components/PermissionRedirect.jsx
- src/sagas/collections.js
- src/sagas/search-reports.js
- src/selectors/ui-flags.js
Change criteria to check if is a UNICEF User
> Change criteria to check if is a UNICEF User

- src/components/Drawer.jsx
- src/lib/constants.js
add Admin link in the side menu if the user is superuser
> add Admin link in the side menu if the user is superuser

- src/pages/Authorized.jsx
[ch32781] Donor - fix Gavi page access, add new filter
> [ch32781] Donor - fix Gavi page access, add new filter

- src/slices/user-groups.js
> Fix master conflicts

- src/components/Drawer.jsx
- src/components/PermissionRedirect.jsx
[ch32785] Donor - if user is GAVI, redirect home page will redirect to GAVI page
> [ch32785] Donor - if user is GAVI, redirect home page will redirect to GAVI page

- src/pages/reports/lib/search-filters-map.js
Could not access Filters in DRP
> Could not access Filters in DRP

- src/pages/reports/lib/search-filters-map.js
> Fix filters display

- src/pages/reports/components/vaccine-type-filter.jsx
- src/pages/reports/search-constants.jsx
GAVI: "Vaccine Type" filter change to multiselect
> GAVI: "Vaccine Type" filter change to multiselect

- src/components/table/search-reports-table.jsx
> Gavi table fix

- src/pages/reports/search-constants.jsx
> Change Vaccine type BE param

- src/components/Content-Header.jsx
CTN list report: would it be possible to have an option of downloading a report.
> CTN list report: would it be possible to have an option of downloading a report.

- src/components/IconTextButton.jsx
- src/components/table/lib/index-search.js
> Fix date format function

- src/components/Content-Header.jsx
- src/lib/constants.js
- src/sagas/search-reports.js
Use custom key for Gavi if user is Unicef
> Use custom key for Gavi if user is Unicef

- src/components/table/search-reports-table.jsx
> GAVI: Remove name column #237

- src/api/search-index.js
- src/components/Content-Header.jsx
- src/components/Drawer.jsx
- src/components/Main.jsx
- src/components/PermissionRedirect.jsx
- src/components/table/search-reports-table.jsx
- src/lib/constants.js
- src/lib/params.js
- src/pages/Authorized.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search.jsx
- src/sagas/search-reports.js
Add new page Gavi adjusting CTN
> Add new page Gavi adjusting CTN

- src/components/Content-Header.jsx
- src/sagas/search-reports.js
> Rename Adjusting param

- package-lock.json
- src/actions/index.js
- src/api/endpoints.js
- src/api/index.js
- src/api/search-index.js
- src/components/Drawer.jsx
- src/components/Main.jsx
- src/components/table/search-reports-table.jsx
- src/lib/constants.js
- src/pages/reports/components/material-code-filter.jsx
- src/pages/reports/components/mou-number-filter.jsx
- src/pages/reports/components/soa-date-filter.jsx
- src/pages/reports/components/unicef-wbs-filter.jsx
- src/pages/reports/constants.jsx
- src/pages/reports/index.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search-constants.jsx
- src/pages/reports/search.jsx
- src/sagas/collections.js
- src/sagas/search-reports.js
add new section: Gavi Statements of Account
> add new section: Gavi Statements of Account

- src/components/Drawer.jsx
- src/lib/constants.js
- src/lib/params.js
> gavi page title adjustment

- src/sagas/search-reports.js
changed source_id to gavi and gavi_soa
>  changed source_id to gavi and gavi_soa

- src/components/table/lib/index-search.js
- src/components/table/search-reports-table.jsx
- src/sagas/search-reports.js
> Small fixes

- src/components/table/search-reports-table.jsx
- src/pages/reports/components/grant-number-filter.jsx
- src/pages/reports/constants.jsx
- src/pages/reports/lib/search-filters-map.js
- src/pages/reports/search-constants.jsx
Gavi Statements of Account changes
> Gavi Statements of Account changes

- src/pages/Authorized.jsx
Gavi Statements of Account access
> Gavi Statements of Account access

- src/components/Content-Header.jsx
- src/components/Drawer.jsx
- src/components/Main.jsx
- src/components/table/search-reports-table.jsx
- src/lib/constants.js
- src/lib/params.js
- src/sagas/search-reports.js
> Add "Covax" Section

- src/components/table/search-reports-table.jsx
- src/pages/reports/lib/search-filters-map.js
Gavi Statements of Account tweaks
> Gavi Statements of Account tweaks
